BEGIN;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_tickets_entregados;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_deuda_abierta;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_top_organizadores;
COMMIT;
